import {
    ClerkProvider,
    SignedIn,
    SignedOut,
    SignIn,
    UserButton,
} from "@clerk/nextjs/app-beta";
import Link from "next/link";
import React from "react";
import "../styles/globals.css";

export const metadata = {
    title: "Next.js",
    description: "Generated by Next.js",
};

function Navbar(): JSX.Element {
    return (
        <div className="w-full max-w-3xl mx-auto h-12 flex justify-between items-center px-4">
            <Link href="/" className="font-bold">
                Home
            </Link>

            <SignedIn>
                <UserButton showName={true} />
            </SignedIn>
        </div>
    );
}

function ContentArea({ children }: { children: React.ReactNode }): JSX.Element {
    return <>{children}</>;
}

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en">
            <ClerkProvider>
                <body className="h-screen w-full">
                    <div className="w-2/3 mx-auto h-full">
                        <Navbar />
                        <SignedOut>
                            <div className="w-full flex justify-center items-center h-full">
                                <SignIn />
                            </div>
                        </SignedOut>
                        <SignedIn>
                            <ContentArea>{children}</ContentArea>
                        </SignedIn>
                    </div>
                </body>
            </ClerkProvider>
        </html>
    );
}
