name: Cypress Tests using Cypress Docker Image

on: 
  push:
    branches:
      - master

jobs:
  test-check-out:
    runs-on: ubuntu-20.04
    defaults:
      run:
        working-directory: application

    strategy:
      matrix:
        node-version: [15]
    steps:
    - uses: actions/checkout@v3
    - uses: pnpm/action-setup@v2
      with:
        version: 7
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'pnpm'
    - name: Install dependencies
      run: pnpm install

cypress-run:
    steps:
      - name: Cypress run
        defaults:
        run:
          working-directory: application
        uses: cypress-io/github-action@v5.1.0 # use the expliciWt version number
        with:
          build: pnpm run build
          start: pnpm start

